name: Test job summaries

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: [linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Build and test
        run: dotnet test