name: Test publish-unit-test-result-action

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: [ubuntu-latest]

    permissions:
      contents: read
      issues: read
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
  
      - name: Restore dependencies
        run: dotnet restore
  
      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --logger "trx;LogFileName=test_results.trx" --results-directory ./test-results

      - name: Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() 
        with:
          files: test-results/test_results.trx